version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: shoppinguser
      DB_PASSWORD: shoppingpassword
      DB_NAME: shopping
      TEST_DB_NAME: shoppingtest
      SECRET: LDJF3408343KL4J4
    depends_on:
      - db
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app

  db:
    image: mysql:8.0
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: shopping
      MYSQL_TEST_DATABASE: shoppingtest
      MYSQL_USER: shoppinguser
      MYSQL_PASSWORD: shoppingpassword
      MYSQL_ROOT_PASSWORD: secret_password
    entrypoint:
      sh -c "
        echo \"CREATE DATABASE IF NOT EXISTS "'\`'"$$MYSQL_TEST_DATABASE"'\`'"; GRANT ALL ON "'\`'"$$MYSQL_TEST_DATABASE"'\`'".* TO '$$MYSQL_USER'@'%';\" > /docker-entrypoint-initdb.d/01.sql;
        /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
